Factory.define :garage, :class => Garage do |f|
  f.title "Hello"
  f.i_am_type "1"
  f.o_id "1"
  f.m_id "1"
  f.address "Hello"
  f.square "1.5"
  f.adv_text "Lorem ipsum dolor sit amet..."
  f.price "1"
  f.currency_id "1"
  f.price_cached "1"
  f.contact_phone "Hello"
  f.contact_email "Hello"
  f.user_id "1"
end